### ISSUE TITLE
Need support for VS 2017

### ISSUE THREAD

**Issue by plexxity** [brunofvalli/NewGuidVSExtension#1]
### Installed product versions
Attempting VS 2017

### Description
This is not working with the latest version of VS 2017

### Steps to recreate
1. Try to install on VS 2017

### Current behavior
Does Not install

### Expected behavior
Should be able to install this on VS 2017

**Comment by brunofvalli** [comment]
I should be able to recompile it for VS2017.

Will take a look over the weekend.

**Comment by brunofvalli** [comment]
Added support on my last sync. 
Try to download again and see if it works out :)

Sorry for the delay.

**Comment by brunofvalli** [comment]
This has been fixed.
